version: "3.9"
services:
  mongo:
    image: mongo
    container_name: mongo
    expose:
      - 27017
  redis:
    image: redis
    container_name: redis
    expose:
      - 6379
  app:
    build: .
    container_name: leaderboard
    ports:
      - "8080:8080"
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mongo
      - redis
    command: bash -c "./wait-for-it.sh mongo:27017 && ./wait-for-it.sh redis:6379 && java -jar app.jar"
